### ISSUE TITLE
simulator reaches terminal states if though no collision takes place.

### ISSUE THREAD

**Issue by mynkpl1998** [mynkpl1998/upgraded-octo-lamp#10]
Configuration to reproduce the result.

Script : test.py

Sim Config
```
config:
  # Simulation Parameters
  t-period: 0.1 # in secs
  
 # IDM settings
   max-speed: 10 # in m/s
   local-view: 20 # in metres (one side)
   cextended-view: 20 # in metres (one side)
   reg-size: 5 # in metres
   cell-size: 1 # in metres

  # Reward Function
  collision-penalty: -10

  # UI settings
  render: true
  fps: 5

  # Set Mode
  mode: 'test'

  # Frame Skip
  frame-skip-value: 1
```
